name: Verify SDK Autogen REST Client

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  verify-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.23.1'

    - name: Run go work sync
      run: go work sync

    - name: Install Swagger
      run: |
        go install github.com/go-swagger/go-swagger/cmd/swagger@latest

    - name: Generate Client
      working-directory: pkg/client-sdk
      run: |
        REST_DIR=tmp make genrest

    - name: Compare Generated Client
      working-directory: pkg/client-sdk
      run: |
        if ! diff -r client/rest/service tmp; then
          echo "Generated client differs from the committed version."
          echo "Please run 'make genrest' locally and commit the changes."
          exit 1
        fi

    - name: Clean up
      working-directory: pkg/client-sdk
      run: rm -rf tmp